spring:
    application:
        name: coursera-principios-de-desenvolvimento-agil-de-software-final-project

    datasource:
        url: jdbc:h2:mem:eu_ja_li
        driverClassName: org.h2.Driver
        username: sa
        password: sa

    jpa:
        open-in-view: false

logging:
    level:
        root: INFO
