spring:    
    devtools:    
        restart:      
            enabled: 'true'      
            poll-interval: '2s'      
            quiet-period: '1s'      
            additional-paths:      
                - src/main/java/

logging:
    level:
        root: INFO
        "[io.github.maiconfz.coursera_principios_de_desenvolvimento_agil_de_software_final_project]": DEBUG
